# .github/workflows/main.yml
name: CI/CD React Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar build
        run: npm run build

      - name: Build finalizado com sucesso
        run: echo "✅ Build concluído com sucesso!"
